### ISSUE TITLE
Prepare deployment environment for version 2

### ISSUE THREAD

**Issue by dialelo** [47deg/scala-exercises#151]
We'll need a list of the software requirements of the Play application in order to provision the servers.

**Comment by raulraja** [comment]
Initially we are planning to deploy in Heroku which supports Play 2 apps out of the box and there is already an app provisioned for it. @rafaparadela has already been given access and just needs to setup the `app.json` required to provision `sass` and the other dependencies.

**Comment by rafaparadela** [comment]
We have merged this advances in `version-2` (PR #164), since we can deploy our branches in prod using the `sbt-heroku` plugin. We only need run:

```bash
sbt clean stage deployHeroku
```

However, we're not able to enable the auto deployment for PRs, since the current structure of the project is not compatible with the existing buildpacks. So I've created the ticket #176 to re-configure the structure of the modules, once we have the compiler project (and maybe others) isolated in sonatype.
