### ISSUE TITLE
Missing Compile Button

### ISSUE THREAD

**Issue by juanpedromoreno** [47deg/scala-exercises#240]
The `Compile` button doesn't appear in this case:

http://jpedrom.es/1SJqEu9

**Comment by rafaparadela** [comment]
@juanpedromoreno In this particular cases shown in the screen captured, the "compile" button is rightly hidden:
- It's hidden in the first exercise because it's successfully resolved (if you change it, then should appear the button).
- In the second one, because not all the inputs are filled.

Anyway, I will take a look to search any unexpected behaviour.

**Comment by juanpedromoreno** [comment]
Thanks @rafaparadela . It makes sense.

**Comment by rafaparadela** [comment]
@juanpedromoreno After researching, certainly an unexpected behaviour occurs that is explained and resolved in this PR #243
